[package]
name = "baremetalisp"
version = "0.1.0"
authors = ["Yuuki Takano <ytakano@wide.ad.jp>, Nobuyuki Kanaya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blisp = { git = "https://github.com/ytakano/blisp.git" }

[profile.dev]
opt-level = 2
lto = true
panic = "abort"

[profile.release]
opt-level = 2
lto = true
panic = "abort"

[lib]
crate-type = ["staticlib"]

[features]
raspi3 = []
raspi4 = []
pine64 = []
