# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Dependencies
        run: sudo apt-get -y install make curl software-properties-common

      - name: Install Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && /bin/bash -c "source $HOME/.cargo/env && export PATH=$HOME/.cargo/bin:$PATH && rustup -y default nightly-2020-05-01 && cargo install cargo-xbuild cargo-binutils"
      
      - name: Install LLVM 10
        run: sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421 && sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" && sudo apt-get -y update && sudo apt-get -y install clang-10 lld-10

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile
        run: cd $GITHUB_WORKSPACE/kernel && /bin/bash -c "source $HOME/.cargo/env && export PATH=$HOME/.cargo/bin:$PATH && make CC=clang-10 LD=lld-10"
